workspace:
  base: /opt
  path: disbursement_services

pipeline:
  test-services:
    image: registry.airwallex.com/java8:build
    pull: true
    volumes:
      - /Storage/Gradle-Cache:/gradle-cache
      - /Storage/Maven-Cache:/root/.m2
      - /Storage/unit-tests:/report
    commands:
      - export TERM=xterm-256color
      - ret=0 && ./gradlew -g /gradle-cache clean build --parallel -Dfile.encoding=UTF8 || ret=$?
      - mkdir -p /report/disbursement_services/${DRONE_REPO_BRANCH//\//-}-${DRONE_BUILD_NUMBER} || true
      - find . -iname tests | xargs -I name cp --parent -r name /report/disbursement_services/${DRONE_REPO_BRANCH//\//-}-${DRONE_BUILD_NUMBER}/
      - 'tput setaf 2 ; echo "report will be at: https://testresults.airwallex.com/unit-tests/disbursement_services/${DRONE_REPO_BRANCH//\//-}-${DRONE_BUILD_NUMBER}/" ; tput sgr0 ;'
      - exit $ret
  build-services:
    image: registry.airwallex.com/java8:build
    pull: true
    volumes:
      - /Storage/Gradle-Cache:/gradle-cache
      - /Storage/Maven-Cache:/root/.m2
    commands:
      - ./gradlew -g /gradle-cache clean bootrepackage --parallel -x test -Dfile.encoding=UTF8
 
